### ISSUE TITLE
[DEV] TVM v0.6 Roadmap

### ISSUE THREAD

**Issue by ZihengJiang** [apache/incubator-tvm#2623]
This roadmap for TVM v0.6. TVM is a community-driven project and we love your feedback and proposals on where we should be heading. Please open up discussion in the discussion forum as well as bring RFCs. 

- Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list).
- Please also check out the [help wanted](https://github.com/dmlc/tvm/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+help+wanted%22) list in the github issues on things that need help

## Features
- Quantization
   - [x] Support for configuring mix-precision
   - [x] Per-Channel scale
   - [x] Graph packing
   - [ ] Smarter calibration algorithm
   - [ ] Model coverage 
   - [ ] Support importing quantization model from other frameworks
- Relay
   - [x] Algebra Data Type
   - [ ] Runtime support for dynamic models
   - [x] Support Any syntax
   - [x] Pass Manager
   - [x] Official text format support
- Automated tuning and scheduling
   - [ ] graph level automated optimization
- Ultra low-bit support 
    - [ ] tutorials of low-bit ops
    - [ ] customized accelerator support
- VTA enhancements
    - [ ] support generic high level models
    - [ ] Enhanced operator/model coverage
    - [ ] Ultra-96, ZCU102 support
    - [ ] Amazon F1 preliminary support
    - [ ] Low-bit support, bit serial support
    - [ ] Chisel version
- Micro-asm kernel exploration
   - [ ] Core micro-asm primitives for certain ops  
- Hybrid python programming model
   - [ ] transition of vision operators to hybrid mode.
- RPC and Device API
  - [ ] Support a c++ version of cross platform RPC
- Training
   - [x] First-order auto differentiation
   - [ ] Gradient operators
   - [x] High-order auto differentiation
- Arithmetics
   - [ ] Formalize Integer Arithmetic Analysis 
- Tutorials
   - [ ] Tutorials of low-bit ops using Relay

**Comment by ehsanmok** [comment]
Besides having some more plans for rust, I'd like creating better tutorials so I want to pick up the _tutorials of low-bit ops_ using relay which is what I've been playing with recently and want to get deeper.

**Comment by icemelon9** [comment]
Does runtime for dynamic model refer to the runtime for Relay? Otherwise, we can also add Relay runtime into 0.6 roadmap.

**Comment by ZihengJiang** [comment]
@edmBernard Great to hear that! Added!

**Comment by ZihengJiang** [comment]
@icemelon9 Right, it refers to the runtime for Relay

**Comment by icemelon9** [comment]
Cool. @jroesch @zhiics @wweic and I can work on runtime for Relay.

**Comment by FrozenGene** [comment]
Wish TVM v0.6 can finish this item: https://github.com/dmlc/tvm/issues/2351. i.e. Support importing exist quantization TFLite model. This can be a start for supporting importing existing quantization model (i.e. don't restrict TFLite).

**Comment by zhiics** [comment]
Pass manager for relay, should be able to finish discussion soon, haha

**Comment by yzhliu** [comment]
does "graph level automated optimization" mean https://github.com/dmlc/tvm/pull/2184 or something else?

**Comment by ZihengJiang** [comment]
@yzhliu I think so. It is a legacy item from roadmap v0.5

**Comment by antinucleon** [comment]
Will work together with @icemelon9 on dynamic runtime.

**Comment by antinucleon** [comment]
I think we should also deprecate nnvm fully in 0.6. So far there are still some legacy code in topi depends on nnvm.

**Comment by icemelon9** [comment]
Could we also add `Any` dimension in the roadmap? I think it's an important feature to have.

**Comment by joshpoll** [comment]
I think official text format support should be part of 0.6. i.e. the parser and printer should be able to support all Relay constructs.

**Comment by yzhliu** [comment]
# TVM Monthly - Feb 2019

# Community
In Feb 2019, we successfully released TVM v0.5 ([release notes](https://github.com/dmlc/tvm/issues/2448)) and made the [roadmap for v0.6](https://github.com/dmlc/tvm/issues/2623).

The community welcomes new Reviewer Zhao Wu (@FrozenGene), Committer Jared Roesch (@jroesch) and PMC member Lianmin Zheng (@merrymercy)

TVM community has voted through Apache Incubation proposal ([#2543](https://github.com/dmlc/tvm/issues/2543)). Markus Weimer posted a proposal to general@incubator.apache.org seeking for ideas and suggestions. The official voting is ongoing on general@ right now.

# Features and Improvements
## Operator Support
* A special operator `annotation.stop_fusion` to prevent it being fused with previous expressions (#2624).
* `batch_matmul`  supported ([#2561](https://github.com/dmlc/tvm/pull/2561)).
* `reverse_reshape` supported ([#2503](https://github.com/dmlc/tvm/pull/2503)).
* Faster-RCNN proposal operator for CUDA ([#2420](https://github.com/dmlc/tvm/pull/2420)).
* Vision operator for YOLO `yolo_reorg` ([#1941](https://github.com/dmlc/tvm/pull/1941)).
* `slice` operator for MXNet ([#2662](https://github.com/dmlc/tvm/pull/2662)).
* `arange` supported ([#2621](https://github.com/dmlc/tvm/pull/2621)).
* Vision operator `roi_align` ([#2618](https://github.com/dmlc/tvm/pull/2618)).
* `where` operator for MXNet ([#2647](https://github.com/dmlc/tvm/pull/2647)).

## User Interface and Frontend
* Introduced `HybridModule` ([#2477](https://github.com/dmlc/tvm/pull/2477)) so that normal TVM schedule can be compiled to hybrid target, run and dumped to Hybrid Script.
* Most frameworks have been supported in Relay, including ONNX, Keras, Tensorflow, Caffe2, CoreML, NNVMv1, MXNet ([#2246](https://github.com/dmlc/tvm/issues/2246)). Siju is working on DarkNet.
* Relay now supports saving and loading parameter dictionaries. ([#2620](https://github.com/dmlc/tvm/pull/2620))
* Rust frontend ([#2292](https://github.com/dmlc/tvm/pull/2292)).
* We are now supporting Tensorflow saved model for NNVM ([#2493](https://github.com/dmlc/tvm/pull/2493/)). Relay support is ongoing ([#2586](https://github.com/dmlc/tvm/pull/2586/)).
* Add `max_num_threads`  to Hybrid Script, which allows users to get max number of threads for GPU targets ([#2672](https://github.com/dmlc/tvm/pull/2672/)).

## Runtime and Hardware Support
* RFC for bringing TVM to Bare-Metal devices ([#2563](https://github.com/dmlc/tvm/issues/2563))
* Make external library extend TVM's NDArray more easily ([#2613](https://github.com/dmlc/tvm/pull/2613)).

## Performance Improvement
* AlterOpLayout pass is now enabled for x86 on Relay ([#2585](https://github.com/dmlc/tvm/issues/2585)). It is essential to get decent performance for CNN-based model on Intel CPUs.

## Documents and Tutorials
* Tutorials for deep learning frameworks support in Relay.
* Tutorial for running AutoTVM with Relay ([#2594](https://github.com/dmlc/tvm/pull/2594)).
* Document for Algebraic Data Types ([#2575](https://github.com/dmlc/tvm/pull/2575)).

##  High-level Optimizations
* An optimization pass to eliminate expressions which have the same functionality and same inputs ([#2639](https://github.com/dmlc/tvm/pull/2639)).
* Provided a pass to calculate the number of multiply-accumulate operations in a network ([#2609](https://github.com/dmlc/tvm/pull/2609)).
* Algebraic Data Types (ADT) support ([#2442](https://github.com/dmlc/tvm/pull/2442), [#2575](https://github.com/dmlc/tvm/pull/2575)). ADT provides an expressive, efficient, and safe way to realize recursive computation (e.g., RNN). Refer to https://docs.tvm.ai/langref/relay_adt.html for more information.
* As a part of Relay's automatic differentiation system, we are adding primal gradients for Relay operators. Please refer to [#2562](https://github.com/dmlc/tvm/issues/2562) for tracking the progress. (**Help wanted**). For automatic differentiation in Relay, also see [Automatic differentiation for tensor expressions](https://github.com/dmlc/tvm/pull/2498), [Higher order reverse mode automatic differentiation that work with control flow](https://github.com/dmlc/tvm/pull/2496), [Tensor Expression level automatic differentiation](https://github.com/dmlc/tvm/issues/1996)
* Low-bit quantization supported ([#2116](https://github.com/dmlc/tvm/pull/2116)). The workflow includes annotation, calibration and transformation. Please also see [Data-Aware Calibration](https://github.com/dmlc/tvm/issues/2651) for calibration algorithm improvement (**Help wanted**). 

## Tensor Expression 
* RFC for formalizing Integer Arithmetic Analysis ([#2588](https://github.com/dmlc/tvm/issues/2588)). It is aiming to perform better context-dependent analysis, bound analysis, centralized arithmetic logic and arithmetic simplification. 

# Contribution and Commits
Thanks Wei @wweic or providing the tools.

## People Who Reviewed Pull Requests
* **tqchen** Runtime, Relay, Tensor Expression, Document, Frontend, AutoTVM
* **were** Runtime, Hybrid Script, TOPI
* **junrushao1994** Runtime, Relay, Hybrid Script
* **ZihengJiang** Relay, Rust, Quantization, Tensor Expression
* **sgrechanik-h** Tensor Expression
* **derisavi** Tensor Expression
* **wweic** Relay 
* **nhynes** Rust, Quantization 
* **ehsanmok** Rust 
* **mjs-arm** Pylint 
* **MarisaKirisame** Relay
* **srkreddy1238** Relay, Tensorflow Frontend, Golang
* **vinx13** Hybrid Script, Relay, TOPI, Quatization
* **kazum** Relay 
* **FrozenGene** TFLite Frontend, AutoTVM, Quantization
* **jroesch** Relay, Rust 
* **zhiics** Relay, Runtime, Tensorflow Frontend
* **imorinaga** Relay(heterogenous annotation)
* **merrymercy** AutoTVM, Tensor Expression, Quantization
* **yzhliu** AutoTVM, Relay, Tensor Expression, Frontend
* **eqy** AutoTVM, Quantization, Relay
* **icemelon9** AutoTVM, Tensor Expression, Runtime, Relay, Frontend 
* **reminisce** Runtime
* **kevinthesun** Tensor Expression, TOPI
* **Anthony-Mai** Tensor Expression
* **slyubomirsky** Relay   
* **joshpoll**  Relay Document
* **eric-haibin-lin** Bugfix
* **ZhennanQin** Bugfix
* **grwlf** Runtime
* **xqdan** Tensor Expression, Hybrid Script
* **Laurawly** Relay, Hybrid Script, TOPI
* **masahi** Relay, TOPI, Document, CodeGen
* **siju-samuel**  Relay
* **PariksheetPinjari909** Operator
* **liangfu** Quantization
* **lixiaoquan** Quantization
* **ajtulloch** Quantization
* **zhreshold** Operator

## People Who Committed
* **tqchen** CI, Runtime, Tensor Expression, Relay Text Printer
* **ruslo** Documents
* **mjs-arm** Pylint, CI
* **vinx13** Relay, TOPI, Operator
* **lixiaoquan** Relay
* **wweic** Relay Document
* **kazum** Tutorial and Document
* **derisavi** Tensor Expression (IntSet)
* **antinucleon** AutoTVM
* **slyubomirsky** Relay (ADT, AutoDiff)
* **MarisaKirisame** Relay
* **junrushao1994** Runtime, Build
* **were** Hybrid Script
* **yidawang** Relay (MAC Calculation)
* **ariwaranosai** Operator
* **ZihengJiang** Relay, Quantization
* **jroesch** Relay
* **hlu1** Runtime
* **headupinclouds** TOPI
* **zhiics** Relay, Tensor Expression
* **weberlo** Relay (param save/load)
* **icemelon9** Tensor Expression, Operator
* **yzhliu** Tensor Expression
* **eqy** Relay, Quantization, AutoTVM tutorial
* **geexie** Bug-fix
* **abergeron** Conda package
* **larroy** NodeEntry Implement Improvement
* **ptrendx** Bug-fix
* **Anthony-Mai** Namespace Fix
* **jdavies-huawei** Tensor Expression
* **srkreddy1238** Tensorflow Frontend, Golang
* **yongwww** Tensorflow Frontend, Relay Document
* **alexeyr** Code Improvement
* **nhynes** Rust
* **makihiro** Caffe2 Frontend
* **kevinthesun** AutoTVM
* **Huyuwei** Tutorial
* **ehsanmok** Rust
* **siju-samuel** Operator
* **sgrechanik-h** Tensor Expression
* **haojin2** Operator
* **SiNZeRo** Document
* **denis0x0D** CodeGen
* **Laurawly** Bug-fix
* **apivovarov** Typo-fix
* **take-cheeze** Typo-fix

## List of Commits
* [BUILD] Simplify after bind device type #2670 (author: tqchen, reviewers: )
* [RUNTIME] Enable NDArray type extension #2598 (author: tqchen, reviewers: ['tqchen', 'were', 'junrushao1994'])
* [EXPR] Expression-template based pattern matching. #2589 (author: tqchen, reviewers: ['tqchen', 'ZihengJiang', 'sgrechanik-h', 'derisavi'])
* [IR] Update HalideIR #2582 (author: tqchen, reviewers: )
* Misc refactor on graph runtime, layout node #2557 (author: tqchen, reviewers: )
* [VERSION] Move version script to the project root #2556 (author: tqchen, reviewers: )
* [RELAY] TextPrinter: Use Map Format #2553 (author: tqchen, reviewers:['wweic'])
* [CI] Update rust format version #2550 (author: tqchen, reviewers: ['tqchen', 'nhynes', 'ehsanmok'])
* [CI] Enable ANTLR in CPU env #2548 (author: tqchen, reviewers: )
* Few docs fixes #2703 (author: ruslo, reviewers: ['tqchen'])
* Pin pylint version 2.2.2 #2698 (author: mjs-arm, reviewers: ['tqchen', 'mjs-arm'])
* [RELAY][PASS] Enable switching CanonicalizeOps in pass_enabled #2696 (author: vinx13, reviewers: ['tqchen'])
* [RELAY] Fix get_int_tuple for shape like '(1001,)' #2691 (author: lixiaoquan, reviewers: ['tqchen'])
* [Relay][Doc] Separate arguments types formatting with comma #2690 (author: wweic, reviewers: ['tqchen', 'MarisaKirisame', 'wweic'])
* [DOC] MXNet frontend tutorial #2688 (author: kazum, reviewers: ['tqchen'])
* [TVM][ARITH] Handle Select in IntSetEvaluator #2687 (author: derisavi, reviewers: ['tqchen'])
* Stop pylint complaining about unnecessary return statement. #2684 (author: mjs-arm, reviewers: ['tqchen'])
* Support mean in NNVM to Relay converter. #2680 (author: lixiaoquan, reviewers: ['tqchen'])
* [Relay] Ensure nested higher-order functions are treated correctly #2676 (author: slyubomirsky, reviewers: ['tqchen'])
* [Relay] fix name in alpha_equal #2674 (author: MarisaKirisame, reviewers: ['tqchen'])
* Minor fix of warnings raised by  -Wreturn-std-move and -Wself-assign-overloaded #2669 (author: junrushao1994, reviewers: ['tqchen', 'junrushao1994'])
* [Relay] fix error in ANF (too agressively inline atomic expression and create free variable). #2665 (author: MarisaKirisame, reviewers: ['tqchen', 'MarisaKirisame'])
* [RUST] ci_cpu docker image build failure. #2657 (author: mjs-arm, reviewers: ['tqchen', 'nhynes'])
* Explicitly disable pylint warning subprocess-popen-preexec-fn #2656 (author: mjs-arm, reviewers: ['tqchen', 'mjs-arm'])
* Stop pylint complaining about useless import alias. #2655 (author: mjs-arm, reviewers: ['tqchen'])
* Adopt pylint suggestion to use dict.get. #2654 (author: mjs-arm, reviewers: ['tqchen', 'mjs-arm'])
* [Relay] fix add-mod #2653 (author: MarisaKirisame, reviewers: ['tqchen', 'MarisaKirisame'])
* [Hybrid Script] Misc fixation #2649 (author: were, reviewers: ['tqchen', 'vinx13'])
* [RELAY][PASS]use attribute registration style in the mac count pass #2645 (author: yidawang, reviewers: ['tqchen'])
* Add CONCATENATION to tflite frontend, support Inception V3 #2643 (author: ariwaranosai, reviewers: ['tqchen', 'srkreddy1238', 'kazum', 'FrozenGene', 'ariwaranosai'])
* Fix pylint 2.2.2 gripes. #2642 (author: mjs-arm, reviewers: ['tqchen'])
* [RELAY][PASS] Common subexpression elimination #2639 (author: vinx13, reviewers: ['tqchen', 'vinx13', 'kazum'])
* [Relay] fix anf for reference and pattern matching #2637 (author: MarisaKirisame, reviewers: ['tqchen', 'ZihengJiang', 'MarisaKirisame'])
* [RELAY/PASS] Change the return value convention of gradient #2635 (author: ZihengJiang, reviewers: ['tqchen', 'ZihengJiang', 'MarisaKirisame', 'jroesch'])
* [RELAY/OP] Gradient of relay level1 ops #2633 (author: ZihengJiang, reviewers: ['tqchen', 'ZihengJiang', 'MarisaKirisame'])
* Add follow up test case for #2601 #2632 (author: jroesch, reviewers: ['tqchen'])
* Fix fusion bug when call symbol that is not an operator. #2630 (author: jroesch, reviewers: ['tqchen'])
* [Bugfix] Missing #include <sstream> #2629 (author: hlu1, reviewers: ['tqchen'])
* [TOPI] remove batch_norm_inference #2626 (author: headupinclouds, reviewers: ['tqchen'])
* [RELAY] Stop_fusion annotation #2624 (author: vinx13, reviewers: ['tqchen', 'vinx13'])
* [Relay]fix heterogenous annotation bug #2622 (author: zhiics, reviewers: ['tqchen', 'kazum', 'zhiics', 'imorinaga'])
* [Relay] Port param dict save/load from NNVM #2620 (author: weberlo, reviewers: ['tqchen', 'weberlo'])
* [autotvm] fix #2617 #2619 (author: antinucleon, reviewers: ['tqchen', 'merrymercy', 'yzhliu', 'eqy', 'icemelon9', 'antinucleon'])
* [TVM][LANG] Add eager simplification for operations with FloatImm #2615 (author: icemelon9, reviewers: ['tqchen', 'icemelon9'])
* [RUNTIME][NDArray] Allowing External Libraries to Subclass NDArrays #2613 (author: junrushao1994, reviewers: ['tqchen', 'were', 'junrushao1994', 'reminisce'])
* [Bugfix] get layout in to_relay #2610 (author: yzhliu, reviewers: ['tqchen', 'icemelon9'])
* [RELAY][PASS] add a relay pass to count #macs of a model #2609 (author: yidawang, reviewers: ['tqchen', 'yzhliu', 'eqy', 'zhiics', 'yidawang'])
* [RELAY][TOPI] `alter_op_layout` for x86 #2602 (author: eqy, reviewers: ['tqchen', 'yzhliu'])
* Fix issue mutating if expressions #2601 (author: jroesch, reviewers: ['tqchen'])
* [DOCS] update titles to reflect tutorial content (nnvm vs. relay) #2597 (author: eqy, reviewers: ['tqchen', 'kevinthesun'])
* [TEST] Remove script that references previously removed content. #2596 (author: mjs-arm, reviewers: ['tqchen'])
* [AUTOTVM][RELAY][DOCS] relay ports of `tune_nnvm_*` autotvm tutorials #2594 (author: eqy, reviewers: ['tqchen', 'eqy', 'FrozenGene'])
A couple of fixes for GEN #2593 (author: geexie, reviewers: ['tqchen', 'geexie'])
* [TUTORIAL] Fix downloaded file path #2590 (author: kazum, reviewers: ['tqchen'])
* [TVM][Bugfix] fix storage_rewrite bug when input is big #2580 (author: zhiics, reviewers: ['tqchen', 'yzhliu', 'wweic', 'zhiics', 'Anthony-Mai'])
* Conda packages with cuda support #2577 (author: abergeron, reviewers: ['tqchen', 'abergeron'])
* Optimize move semantics of NodeEntry reducing copies of shared_ptr wh… #2576 (author: larroy, reviewers: ['tqchen'])
* [Relay][Docs] Documentation for Algebraic Data Types #2575 (author: slyubomirsky, reviewers: ['tqchen', 'slyubomirsky', 'wweic', 'zhiics', 'joshpoll', 'junrushao1994'])
* fix typo #2574 (author: MarisaKirisame, reviewers: ['tqchen'])
* Fix the FInplaceIdentity #2572 (author: ptrendx, reviewers: ['tqchen', 'yzhliu', 'eric-haibin-lin', 'ptrendx', 'ZhennanQin'])
* [TVM] [NNVM] Namespace pollution and name conflict of NodePtr #2571 (author: Anthony-Mai, reviewers: ['tqchen', 'Anthony-Mai'])
* [Graph Runtime] Run_individual for benchmarking individual layers #2569 (author: hlu1, reviewers: ['tqchen', 'icemelon9', 'zhiics', 'grwlf', 'hlu1'])
* Tighten buffer bound for TensorComputeOp by improving EvalSet on ranges #2565 (author: jdavies-huawei, reviewers: ['tqchen', 'xqdan', 'jdavies-huawei'])
* [Relay/TOPI][Op] Add batch_matmul in relay and TOPI #2561 (author: icemelon9, reviewers: ['tqchen', 'Laurawly', 'icemelon9'])
[Golang] bugfix #2517 #2558 (author: srkreddy1238, reviewers: ['tqchen', 'srkreddy1238'])
* [COMMUNITY] @FrozenGene -> Reviewer #2544 (author: ZihengJiang, reviewers: ['tqchen', 'icemelon9'])
* [RELAY] Copy subfunction arguments to output tuple field #2537 (author: vinx13, reviewers: ['tqchen', 'masahi'])
print ast w/o metadata #2533 (author: zhiics, reviewers: ['tqchen', 'jroesch', 'zhiics'])
* [DOCS][RELAY] Sync up ops with code base #2532 (author: yongwww, reviewers: ['tqchen', 'yongwww'])
* Remove duplicate as Checks and CHECK value #2531 (author: alexeyr, reviewers: ['tqchen', 'alexeyr', 'Anthony-Mai'])
add `min_repeat_ms` to other CUDA tutorials #2526 (author: eqy, reviewers: ['tqchen', 'vinx13'])
* [Rust] Update rustc #2524 (author: nhynes, reviewers: ['tqchen'])
* [Lang] Layout in TVM node system #2509 (author: yzhliu, reviewers: ['tqchen', 'merrymercy', 'yzhliu', 'kevinthesun'])
* [Relay][Frontend] Caffe2 Support #2507 (author: makihiro, reviewers: ['tqchen', 'yzhliu', 'kazum', 'makihiro'])
* [Relay][OP] Add reverse_reshape #2503 (author: icemelon9, reviewers: ['tqchen', 'yzhliu', 'vinx13', 'icemelon9', 'jroesch', 'junrushao1994'])
* [Relay] GNF #2492 (author: MarisaKirisame, reviewers: ['tqchen', 'MarisaKirisame', 'slyubomirsky'])
* Add fallback for ApplyGraphBest #2485 (author: kevinthesun, reviewers: ['tqchen', 'merrymercy', 'kevinthesun'])
* [TEST] Remove script that references previously removed content. #2481 (author: mjs-arm, reviewers: ['tqchen'])
* [Tutorial][Frontend] move from_keras tutorial to frontend #2479 (author: Huyuwei, reviewers: ['tqchen', 'Huyuwei', 'eqy'])
* [Hybrid script] Backend support #2477 (author: were, reviewers: ['tqchen', 'Laurawly', 'vinx13', 'were', 'xqdan', 'junrushao1994'])
* [TOPI][CUDA] Add faster-rcnn proposal op #2420 (author: vinx13, reviewers: ['tqchen', 'masahi', 'Laurawly', 'vinx13', 'were', 'kevinthesun'])
* [RUST][FRONTEND] Add rust frontend v0.1 #2292 (author: ehsanmok, reviewers: ['tqchen', 'ZihengJiang', 'nhynes', 'jroesch', 'ehsanmok'])
* REGION op removed from topi and added in darkent frontend #2275 (author: siju-samuel, reviewers: ['tqchen', 'siju-samuel', 'PariksheetPinjari909', 'jroesch'])
* [RELAY][FRONTEND] Tensorflow frontend. #2216 (author: srkreddy1238, reviewers: ['tqchen', 'srkreddy1238', 'yzhliu', 'kazum', 'jroesch', 'yongwww'])
* [OPT] Low-bit Quantization #2116 (author: ZihengJiang, reviewers: ['tqchen', 'ZihengJiang', 'merrymercy', 'vinx13', 'eqy', 'nhynes', 'jroesch', 'liangfu', 'lixiaoquan', 'ajtulloch', 'FrozenGene'])
* [RELAY]Vision ops for yolo #1941 (author: siju-samuel, reviewers: ['tqchen', 'siju-samuel', 'yzhliu'])
* [Quantize] Skip for same input-output domain scale. #2611 (author: ZihengJiang, reviewers: ['vinx13', 'eqy'])
* Version 0.5 #2604 (author: ZihengJiang, reviewers: ['ZihengJiang', 'yzhliu', 'Laurawly', 'icemelon9', 'jroesch'])
* [BUGFIX] Fix for quantize. #2573 (author: ZihengJiang, reviewers: ['eqy'])
* [Quantization][RELAY] Add check against NCHWc ops in the quantization pass #2646 (author: eqy, reviewers: ['ZihengJiang'])
* [TVM][BUGFIX] Fix missing reduction init predicates #2495 (author: sgrechanik-h, reviewers: ['ZihengJiang', 'sgrechanik-h'])
* [Relay] Reference #2489 (author: MarisaKirisame, reviewers: ['ZihengJiang', 'MarisaKirisame', 'slyubomirsky', 'zhiics'])
* [relay][frontend] TensorFlow saved model support #2586 (author: yongwww, reviewers: ['srkreddy1238', 'zhiics', 'yongwww'])
* [Tensorflow Frontend] Add saved model support and infer shape w/o add_shapes=True #2493 (author: yongwww, reviewers: ['tqchen', 'srkreddy1238', 'yzhliu', 'zhiics', 'yongwww'])
* [Python dep] Add missing dep pkg for relay #2568 (author: antinucleon, reviewers: ['srkreddy1238'])
* [COMMUNITY] @merrymercy -> PMC #2578 (author: yzhliu, reviewers: ['eqy'])
* [DOC] CoreML frontend tutorial #2667 (author: kazum, reviewers: ['yzhliu', 'kazum', 'zhiics'])
* [Frontend][MXNet] Add MXNet frontend converter for slice operator #2662 (author: haojin2, reviewers: ['yzhliu', 'haojin2'])
* Fix missing argument for NCHWc in Relay #2627 (author: eqy, reviewers: ['yzhliu'])
* [Relay/TOPI][OP] Add arange op in Relay and TOPI #2621 (author: icemelon9, reviewers: ['yzhliu', 'Laurawly', 'icemelon9', 'zhreshold', 'zhiics'])
* [RELAY][DOCS] Port from_mxnet tutorial to relay #2608 (author: eqy, reviewers: ['yzhliu', 'eqy', 'zhreshold'])
* Fix typo #2595 (author: icemelon9, reviewers: ['yzhliu'])\
* [DOC] Using External Libraries in Relay #2694 (author: SiNZeRo, reviewers: ['masahi', 'SiNZeRo'])
* [CODEGEN NVPTX] Initialize llvm before lookup for the target #2683 (author: denis0x0D, reviewers: ['masahi', 'denis0x0D'])
* [RELAY][OP] ROI Align #2618 (author: vinx13, reviewers: ['masahi', 'Laurawly', 'vinx13'])
* [Bugfix] Nms_ir data_race solved #2600 (author: Laurawly, reviewers: ['masahi', 'Laurawly', 'vinx13'])
* [Hybrid Script] Add `max_num_threads` #2672 (author: were, reviewers: ['Laurawly', 'vinx13', 'were'])
* [DOCKER][FRONTEND] Run DarkNet tests #2673 (author: kazum, reviewers: ['kazum'])
* [COMMUNITY] @jroesch -> Committer #2661 (author: icemelon9, reviewers: ['eqy'])
* Fix typo in Evaluate inference time cost code #2542 (author: apivovarov, reviewers: ['eqy'])
* Fix typo #2681 (author: take-cheeze, reviewers: ['nhynes'])
* [Relay] add more function to prelude #2660 (author: MarisaKirisame, reviewers: ['MarisaKirisame', 'wweic'])
* [Relay] add more descriptive error for checked_type #2652 (author: MarisaKirisame, reviewers: ['MarisaKirisame'])
* [Frontend][MXNet] Add MXNet frontend converter for where operator #2647 (author: haojin2, reviewers: ['icemelon9'])
* [Relay] Fixes to sum #2439 (author: jroesch, reviewers: ['jroesch'])
* Docker updates #2702 (author: mjs-arm, reviewers: )

**Comment by jroesch** [comment]
We (@yongwww, @zhiics and I) will be providing support for loops and conditionals for the TensorFlow frontend soon.

**Comment by FrozenGene** [comment]
@jroesch Awesome. Using AOT relay runtime?

**Comment by ajtulloch** [comment]
@jroesch that's wonderful, very excited to see how that turns out :)

**Comment by zhiics** [comment]
@FrozenGene It uses the interpreter.
@ajtulloch We used something like "pattern matching" to identify the scope/execution frame a control flow op and converted them into Relay recursive call and If constructs. We will send out the PR soon.

**Comment by tqchen** [comment]
@zhiics @jroesch as per community tradition, it would be great to send out an RFC first to describe the proposal of such major change, before we do the PR

**Comment by zhiics** [comment]
@tqchen No worries. We will.

**Comment by merrymercy** [comment]
# TVM Monthly - March 2019
https://discuss.tvm.ai/t/tvm-monthly-march-2019/2083

**Comment by ZihengJiang** [comment]
# TVM Monthly - April 2019
https://discuss.tvm.ai/t/tvm-monthly-april-2019/2426

**Comment by icemelon9** [comment]
# TVM Monthly - May 2019
https://discuss.tvm.ai/t/tvm-monthly-may-2019/2793

**Comment by yzhliu** [comment]
# TVM Monthly - June 2019

https://discuss.tvm.ai/t/tvm-monthly-june-2019

**Comment by kparzysz-quic** [comment]
What is the planned release date for 0.6?

**Comment by tqchen** [comment]
There has been quite a lot of improvements recently. While it is up to the community, I think we might be able to get out something around Sep

**Comment by Lyken17** [comment]
> - [ ]  graph level automated optimization

Does it mean traditional fusion / layout transform, or more recent graph substitution like [this paper](https://www.sysml.cc/doc/2019/22.pdf)? If the later one, I would like to port my onnx implementation to TVM.

**Comment by MarisaKirisame** [comment]
Higher order automatic differentiation was done like half years ago. Please check that.

**Comment by merrymercy** [comment]
@Lyken17 https://github.com/dmlc/tvm/issues/1585

**Comment by icemelon9** [comment]
# TVM Monthly - July 2019
https://discuss.tvm.ai/t/tvm-monthly-july-2019

**Comment by ZihengJiang** [comment]
@MarisaKirisame Checked. I listed it here just because that it did not go into the last release cycle

**Comment by snowolfhawk** [comment]
Hybrid python programming model
  transition of vision operators to hybrid mode.

what's plan for this feature?

**Comment by zhiics** [comment]
# TVM Monthly - August 2019

https://discuss.tvm.ai/t/tvm-monthly-august-2019

**Comment by icemelon9** [comment]
# TVM Monthly - September 2019
https://discuss.tvm.ai/t/tvm-monthly-september-2019

**Comment by xqdan** [comment]
When will we have 0.6 release ? thanks

**Comment by yzhliu** [comment]
# TVM Monthly - October 2019
https://discuss.tvm.ai/t/tvm-monthly-oct-2019/4587

**Comment by tqchen** [comment]
Move to #4259
